<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>

<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>


<script type="text/javascript">
var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<?php echo $this->getChildHtml('product_type_data') ?>



<?php 
	
	/* Define se a url enviará para o carrinho, ou se será uma url de inscrição de produto sem estoque */
	
	$_storeId = Mage::app()->getStore()->getId(); 
	$_isActive = Mage::getStoreConfig('outofstocksubscription/mail/active', $_storeId);
	
	if(!$_product->isSaleable() && $_isActive){
		
		$_url = $this->getUrl('outofstocksubscription');
		
	} else {
		
		$_url = $this->getSubmitUrl($_product);
		
	}
?>



<form action="<?php echo $_url ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>	

	<div class="no-display">
		<?php echo $this->getBlockHtml('formkey'); ?>
		<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
	    <input type="hidden" name="related_product" id="related-products-field" value="" />
	</div>

	<div id="colunas12"></div>

	<div id="colunas6">
		<?php echo $this->getChildHtml('media') ?>
	</div>

	<div id="<?php echo $_product->getUrlPath(); ?>">

		<div id="colunas6" class="no-bottom">

			<h1 class="bold cor fs-24 d-b ta-c"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>

		    <p class="fs-14 cod ta-c">C&oacute;d. do Produto: <?php echo $_product->getSku() ?></p>

		    <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
		    <?php echo $this->getChildHtml('alert_urls') ?>

			<?php 
			$newFromDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsFromDate();
			$newToDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsToDate();
			$now = date("Y-m-d");

			if($newFromDate < $now && $newToDate >= $now): ?>
				<p class="novo">novidade</p>
			<?php endif; ?>
            <div class="h-r f-l d-b"></div>
		</div>
	</div>

	<div id="colunas6" class="ta-c no-bottom product-page">
        <br>

        <?php if($_product->getData('brinde')): ?>
            <div class="product-promo product-promo-gift">
                <strong>GANHE BRINDE:</strong> <?php echo $_product->getData('brinde'); ?>
            </div>
        <?php endif; ?>
        <div class="product-promo-free-shipping">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/default/adaptive-shop/images/icon-frete.svg" width="30px">
            <strong>Frete Grátis</strong> nas compras acima de R$ 189,00*
        </div>

        <?php echo $this->getPriceHtml($_product, true) ?>
		
		<div id="price-installments" style="width: auto;height: auto;margin: 0 auto;max-width: 410px;display: inline-block;">

		</div>

        <br>
	</div>

    <div id="colunas6" class="no-bottom">

        <div class="h-r f-l d-b"></div><br />
        
        <div class="product-options" id="product-options-wrapper">
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
        <?php endif;?>

        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?><br />
        <?php endif;?>
        </div>

        <div class="product-info no-bottom ta-c">

            <div id="product-price">
                <br />

                <?php if ($_product->isSaleable() && !$this->hasOptions()):?>
                    <div class="list-qtd product-simple-quantity">
                        <span class="less">-</span>
                        <input style="width:48px !important;float:none;text-align:center;margin-top: 0px;" class="op-i" type="text" name="qty" id="qty" maxlength="6" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>" />
                        <span class="more">+</span>
                    </div>
                <?php endif ?>

                <?php if ($_product->isSaleable() && $_product->isConfigurable()):?>
                    <div class="list-qtd product-simple-quantity">
                        <span class="less">-</span>
                        <input style="width:48px !important;float:none;text-align:center;margin-top: 0px;" class="op-i" type="text" name="qty" id="qty" maxlength="6" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>" />
                        <span class="more">+</span>
                    </div>
                <?php endif ?>

                <?php if($_product->isSaleable()): ?>
                    <input type="submit" value="COMPRAR" class="bt-buy-nova cor-sec d-b fs-20 radius bold validation-passed" onclick="productAddToCartForm.submit(this); return false;">
                <?php else: ?>

                    <img class="prod-esg" src="<?php echo $this->getUrl('') ?>skin/frontend/default/adaptive-shop/images/ProdutoEsgotado-2x.png" alt="Produto Esgotado" width="250" />

                    <?php if(!$_product->isSaleable() && $_isActive): ?>

                        <div class="out_of_stock_notification">
                            <h3 class="bold fs-16 cor">Preencha seu email abaixo para avisarmos quando ele estiver disponível</h3>
                            <div class="form_out_of_stock">
                                <input type="text" id="subscription_email" name="subscription_email" value="" placeholder="email" class="input-text d-b op-i txt fs-14 required-entry validate-email op-i" />
                                <button onclick="productAddToCartForm.submit();" class="button btn-cart" type="button"><?php echo $this->__('Subscribe') ?></button>
                            </div>
                        </div>

                    <?php endif; ?>

                <?php endif; ?>
            </div>

        </div>

    </div>



</form>

<div id="colunas12">
    <div class="tabs">
        <ul class="tab-links">
            <li class="active"><a href="#tab1">Descrição</a></li>

            <?php if($_product->getData('sugestoes_de_uso')): ?>
                <li><a href="#tab2">Sugestões de Uso</a></li>
            <?php endif; ?>

            <?php if($_product->getData('tabela_nutricional') != "no_selection"): ?>
                <li><a href="#tab3">Tabela Nutricional</a></li>
            <?php endif; ?>

            <?php if($_product->getData('ingredientes_informacoes')): ?>
                <li><a href="#tab4">Ingredientes e Informações Nutricionais</a></li>
            <?php endif; ?>
        </ul>

        <div class="tab-content">
            <div id="tab1" class="tab active">
                <?php echo $_product->getDescription(); ?>
            </div>
            <div id="tab2" class="tab">
                <?php if($_product->getData('sugestoes_de_uso')): ?>
                    <?php echo $_product->getData('sugestoes_de_uso'); ?>
                <?php endif; ?>
            </div>
            <div id="tab3" class="tab">
                <?php if($_product->getData('tabela_nutricional') != "no_selection"): ?>
                    <?php
                        $imageSrc = $_product->getData('tabela_nutricional');
                        $ThumbnailUrl = Mage::getBaseUrl('media').'catalog/product'.$imageSrc;
                        echo "<img src='{$ThumbnailUrl}' />";
                    ?>
                <?php endif; ?>
            </div>
            <div id="tab4" class="tab">
                <?php if($_product->getData('ingredientes_informacoes')): ?>
                    <?php echo $_product->getData('ingredientes_informacoes'); ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<div id="colunas12">
    <div id="anchor-c" class="f-l d-ib"></div>
    <?php echo $this->getChildHtml('reviews') ?>
</div>

<div id="colunas12" class="product-info no-bottom ta-c">
    <?php echo $this->getChildHtml('related') ?>
</div>

<div id="colunas12" class="product-info">
    <?php echo $this->getChildHtml('upsell_products') ?>
</div>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('.tabs .tab-links a').on('click', function(e)  {
            var currentAttrValue = jQuery(this).attr('href');
            // Show/Hide Tabs
            jQuery('.tabs ' + currentAttrValue).slideDown(400).siblings().slideUp(400);
            // Change/remove current tab to active
            jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
            e.preventDefault();
        });
    });
</script>

<script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
</script>

</div>
</div>

<script>
	
	var msgSuccess = "";
	
	<?php if ($_url == $this->getUrl('outofstocksubscription')): ?>
		msgSuccess = "Avisaremos assim que o seu produto, estiver disponível!";
	<?php endif ?>
	
	jQuery("body.catalog-product-view #review-form button").click(function(){
		msgSuccess = "Seu comentário foi enviado com sucesso!";
		localStorage.setItem("message", msgSuccess);
	});
	
	jQuery("body.catalog-product-view .btn-cart").click(function(){
		localStorage.setItem("message", msgSuccess);
	});
		
</script>

<script>

    jQuery('.dropdown-el.bundle').click(function(e) {
        e.preventDefault();
        e.stopPropagation();
        jQuery(this).toggleClass('expanded');
        jQuery('#'+jQuery(e.target).attr('for')).prop('checked',true);

        if(!jQuery(this).hasClass('prod-select-option')){
            bundle.changeSelection(document.getElementById(jQuery(e.target).attr('for')));
        }

    });

    jQuery(document).click(function() {
        jQuery('.dropdown-el.bundle').removeClass('expanded');
    });

</script>

<div id="full" class="no-home">
	<div id="wrapper">