<li>
    <a href="/acessorios">Acessórios</a>
    <ul class="dl-submenu">
        <li>
            <a href="/acessorios/bolsas-para-refeicoes">Bolsas para Refeições</a>
        </li>
        <li>
            <a href="/acessorios/botinhas-de-treino">Botinhas de Treino</a>
        </li>
        <li>
            <a href="/acessorios/cintos">Cintos</a>
        </li>
        <li>
            <a href="/acessorios/coqueteleiras">Coqueteleiras</a>
        </li>
        <li>
            <a href="/acessorios/joelheiras">Joelheiras</a>
        </li>
        <li>
            <a href="/acessorios/luvas">Luvas</a>
        </li>
        <li>
            <a href="/acessorios/outros">Outros</a>
        </li>
        <li>
            <a href="/acessorios/porta-capsulas">Porta Cápsulas</a>
        </li>
    </ul>
</li>

<li>
    <a href="/emagrecedores">Emagrecedores</a>
    <ul class="dl-submenu">
        <li>
            <a href="/emagrecedores/bloqueadores-e-inibidores">Bloqueadores e Inibidores</a>
        </li>
        <li>
            <a href="/emagrecedores/cafeina">Cafeína</a>
        </li>
        <li>
            <a href="/emagrecedores/cl-la-cromo">CL - LA - Cromo</a>
        </li>
        <li>
            <a href="/emagrecedores/diureticos">Diuréticos</a>
        </li>
        <li>
            <a href="/emagrecedores/gourmet">Gourmet</a>
        </li>
        <li>
            <a href="/emagrecedores/l-carnitina">L-Carnitina</a>
        </li>
        <li>
            <a href="/emagrecedores/outros">Outros</a>
        </li>
        <li>
            <a href="/emagrecedores/shakes">Shakes</a>
        </li>
        <li>
            <a href="/emagrecedores/termogenicos">Termogênicos</a>
        </li>
    </ul>
</li>

<li>
    <a href="/energia-e-resistencia">Energia e Resistência</a>
    <ul class="dl-submenu">
        <li>
            <a href="/energia-e-resistencia/barrinhas-energeticas">Barrinhas Energéticas</a>
        </li>
        <li>
            <a href="/energia-e-resistencia/carboidratos">Carboidratos</a>
        </li>
        <li>
            <a href="/energia-e-resistencia/oleos-e-efas">Óleos e EFAs</a>
        </li>
        <li>
            <a href="/energia-e-resistencia/outros">Outros</a>
        </li>
        <li>
            <a href="/energia-e-resistencia/pre-treinos">Pré-Treinos</a>
        </li>
        <li>
            <a href="/energia-e-resistencia/repositor-energetico">Repositor Energético</a>
        </li>
    </ul>
</li>

<li>
    <a href="/kits-exclusivos">Kits Exclusivos</a>
    <ul class="dl-submenu">
        <li>
            <a href="/kits-exclusivos/kits-de-acessorios">Kits de Acessórios</a>
        </li>
        <li>
            <a href="/kits-exclusivos/kits-definicao">Kits Definição</a>
        </li>
        <li>
            <a href="/kits-exclusivos/kits-emagrecimento">Kits Emagrecimento</a>
        </li>
        <li>
            <a href="/kits-exclusivos/kits-energia-e-resistencia">Kits Energia e Resistência</a>
        </li>
        <li>
            <a href="/kits-exclusivos/kits-massa-muscular">Kits Massa Muscular</a>
        </li>
    </ul>
</li>

<li>
    <a href="/massa-muscular">Massa Muscular</a>
    <ul class="dl-submenu">
        <li>
            <a href="/massa-muscular/aminoacidos">Aminoácidos</a>
        </li>
        <li>
            <a href="/massa-muscular/bcaa-s">BCAA's</a>
        </li>
        <li>
            <a href="/massa-muscular/colageno-e-nutricosmeticos">Colágeno e Nutricosméticos</a>
        </li>
        <li>
            <a href="/massa-muscular/creatina-e-glutamina">Glutamina e Outros</a>
        </li>
        <li>
            <a href="/massa-muscular/hipercaloricos">Hipercalóricos</a>
        </li>
        <li>
            <a href="/massa-muscular/outros">Outros</a>
        </li>
        <li>
            <a href="/massa-muscular/polivitaminicos">Polivitamínicos</a>
        </li>
        <li>
            <a href="/massa-muscular/proteinas">Proteínas</a>
        </li>
        <li>
            <a href="/massa-muscular/whey-protein">Whey Protein</a>
        </li>
    </ul>
</li>

<div class="bg-menu"></div>

