<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
USAGE:

Simple:

<?php echo $this->getLayout()->createBlock('customer/widget_dob')
   ->setDate($this->getCustomer()->getDob())
   ->toHtml() ?>

For checkout/onepage/billing.phtml:

<?php echo $this->getLayout()->createBlock('customer/widget_dob')
   ->setDate($this->getCustomer()->getDob())
   ->setFieldIdFormat('billing:%s')
   ->setFieldNameFormat('billing[%s]')
   ->toHtml() ?>

NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css
      Alternatively we could calculate widths automatically using block input parameters.
*/

/**
 * @see Mage_Customer_Block_Widget_Dob
 */
?>
<label for="<?php echo $this->getFieldId('month')?>" class="txt fs-12<?php if ($this->isRequired()) { echo ' required'; } ?>"><?php echo $this->__('Date of Birth') ?></label>
<div class="input-box customer-dob">
  <div class="dob-day f-l" style="height:18px;margin:7px 3px 6px 0;">
    <select name="<?php echo $this->getFieldName('day'); ?>" id="<?php echo $this->getFieldId('day'); ?>">
      <option value=""><?php echo $this->__('DD'); ?></option>
      <?php for ($i = 1; $i <= 31; $i++): ?>
      <?php $day = (strlen($i) == 1) ? "0" . $i : $i; ?>
        <option value="<?php echo $day; ?>" <?php echo ($i==$this->getDay()) ? "selected" : ""; ?>><?php echo $day; ?></option>
      <?php endfor; ?>
    </select>
  </div>
  <div class="dob-month f-l" style="height:18px;margin:7px 3px 6px 0;">
    <select name="<?php echo $this->getFieldName('month'); ?>" id="<?php echo $this->getFieldId('month'); ?>">
      <option value=""><?php echo $this->__('MM'); ?></option>
      <?php for ($i = 1; $i <= 12; $i++): ?>
      <?php $month = (strlen($i) == 1) ? "0".$i : $i; ?>
        <option value="<?php echo $month; ?>" <?php echo ($i==$this->getMonth()) ? "selected" : ""; ?>><?php echo $month; ?></option>
      <?php endfor; ?>
    </select>
  </div>
  <div class="dob-year f-l" style="height:18px;">
    <?php $currentYear = intval(date("Y")); ?>
    <select name="<?php echo $this->getFieldName('year'); ?>" id="<?php echo $this->getFieldId('year'); ?>" style="width:52px;margin:7px 0 6px 0;">
      <option value=""><?php echo $this->__('YYYY'); ?></option>
      <?php for ($i = $currentYear; $i >= $currentYear - 100; $i--): ?>
        <option value="<?php echo $i; ?>" <?php echo ($i==$this->getYear()) ? "selected" : ""; ?>><?php echo $i; ?></option>
      <?php endfor; ?>
    </select>
  </div>
  <div class="dob-full" style="display:none;">
    <input type="hidden" id="<?php echo $this->getFieldId('dob')?>" name="<?php echo $this->getFieldName('dob')?>" />
  </div>
  <div class="validation-advice" style="display:none;"></div>
</div>
<script type="text/javascript">
//<![CDATA[
    var DOBSelects = Class.create(Varien.DOB, {
       initialize: function(selector, required, format) {
            var el = $$(selector)[0];
            var container       = {};
            container.day       = Element.select(el, '.dob-day select')[0];
            container.month     = Element.select(el, '.dob-month select')[0];
            container.year      = Element.select(el, '.dob-year select')[0];
            container.full      = Element.select(el, '.dob-full input')[0];
            container.advice    = Element.select(el, '.validation-advice')[0];
            new Varien.DateElement('container', container, required, format);
        }      
    });
    var customer_dob = new DOBSelects('.customer-dob', <?php echo $this->isRequired() ? 'true' : 'false' ?>, '<?php echo $this->getDateFormat() ?>');
//]]>
</script>